### ISSUE TITLE
[Discuss] Credential selection vs. wallet selection

### ISSUE THREAD

**Issue by timcappalli** [WICG/identity-credential#27]
> Surfaced as a core discussion topic on the first call ([2023-10-04](https://github.com/WICG/identity-credential/wiki/2023-10-04-Meeting-Notes)).

**Comment by timcappalli** [comment]
Extensive discussions at IIW and [2023-10-18 call](https://github.com/WICG/identity-credential/wiki/2023-10-18-Meeting-Notes#credential-vs-wallet-selection).

General consensus at both IIW and the call was for credential selection for presentation with the ability to surface wallet UI. 

Leaving this issue open until **11/1** for any additional comments.

**Comment by Sakurann** [comment]
to be honest, I am not entirely comfortable with the framing `credential selection vs wallet selection`. 

If this is about the mobile OS assisted user consent screen, can this be reframed to be "the granularity of information based on which the user is providing consent in the mobile OS controlled screen"? In which case, I agree it should be credential-level: it is clearer than displaying the wallet apps and more privacy preserving than displaying attributes. (Though since this is a forum to talk about browser API part of the platform-assisted credential presentation, maybe this is out of scope?)

If this is about what is being returned as the result of the browser API call, both options of the wallet returning either a credential of a wallet endpoint is still on the table AFAIK.

**Comment by timcappalli** [comment]
2023-11-06 call: "credential-based wallet selector" may be a better way to refer to this.

**Comment by RByers** [comment]
FWIW "credential-based wallet selector" makes a ton of sense to me. Certainly it's the wallet that's gathering consent, making a lot of the trust decisions, etc. I'd argue the platform is just playing a small role in mediating the interaction with the wallet (rather than doing the job of a wallet). So sounds like we're on the same page here.

**Comment by timcappalli** [comment]
Closing after 2+ week waiting period and discussion on 2023-11-06 call.
